### ISSUE TITLE
BFT scenario: timeout/retry on io.lettuce.core.RedisCommandInterruptedException

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#146]
API service talks to Redis before making a call to Hello, upon return of this error, application retires 10x with a 3 second delay between calls.

Verify that the test returns in some number of milliseconds.

**Comment by MichaelA-ops** [comment]
Should all the retires also return RedisCommandInterruptedException?

**Comment by cmeiklejohn** [comment]
Filibuster should automatically do that, by injecting the first fault, triggering the retry and in a subsequent test failing the retry (as long as `suppressCombinations=false`.)
