### ISSUE TITLE
Flowchart

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#213]
We need a flow chart of the execute method for the FilibusterGrpcTest.  We should write this down as an outline before diagramming it to make sure.

It needs to be abstract enough that it can fit on a page and be clear, but detailed enough that we should be able to map each of our new subclass extensions into it.

The easiest way to construct this is probably to think about the testing passes and how the system address them:

For example:

  - [ ] Reference Execution
  - [ ] Reference Execution with Stub/Verify Checking
  - [ ] Single Fault Execution, for injected fault
      - [ ] Verify that the user specified the behavior when fault injected
      - [ ] Verify that the user specified behavior is correct
          - [ ] _Effectively all these do is allow us to change the assertion block with shorthands for writing new assertion blocks with differential for stub assertions._
          - [ ] No effect, normal assertions (no assertion impact)
          - [ ] Thrown exception, specified error code and specified error code assertions
          - [ ] New assertions (assertion impact)
          - [ ] Propagation of Error
  - [ ] Multiple Fault Execution
      - [ ] Compositionally Verify?  If outcome is non-ambiguous.

**Comment by MichaelA-ops** [comment]
https://lucid.app/lucidchart/f89e6c93-23ef-453e-adc3-aec5b33acee7/edit?invitationId=inv_d3a3da56-0cf7-4161-9761-e683757f31bd&page=0_0#
