### ISSUE TITLE
new tests cause file descriptor limit failure

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#242]
![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/22aca67d-0e1a-4fd8-8136-210bde80a8fa)

I suggest finding a way, that doesn't involve the person setting a new limit and rebooting their computer, to run the test suite without failures.  Perhaps you can simplify this example, data, or the ways in which faults are injected to reduce this.

**Comment by cmeiklejohn** [comment]
![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/e70b0ebd-28fb-4606-86b9-39013a28e144)

**Comment by cmeiklejohn** [comment]
Disabling this test until resolved.

**Comment by MichaelA-ops** [comment]
Closed for now since tests are passing
