### ISSUE TITLE
test suite not passing locally

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#261]
![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/da77000c-7be5-4595-a1f1-5b5772f213ef)

**Comment by MichaelA-ops** [comment]
![Screenshot 2023-08-15 at 14 23 06](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/74309722/c084204c-dde5-450a-b638-ed4a21d3e03a)
I couldn't reproduce the failure locally. Which branch is this? What exception are they failing with?

**Comment by cmeiklejohn** [comment]
file descriptors

**Comment by MichaelA-ops** [comment]
Could you please check if https://github.com/filibuster-testing/filibuster-java-instrumentation/pull/260/commits/50cdc96bfc556441982a15840fadae8d5981409a fixes it?

**Comment by cmeiklejohn** [comment]
looks good, I pulled it into my branch.
