### ISSUE TITLE
Fix HTML output for Filibuster runs.

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#65]
Ensure that:

* [x] When a new Filibuster run happens:
    * [x] the HTML placeholder file is written out at the start of the test: immediately.  
    Right now, I think it's happening after the initial test execution completes.
    * [x] the /tmp/filibuster directory is cleared out, otherwise test output will accumulate forever.

This is a good way to understand the full lifecycle from test to HTML output.

**Comment by jiujiu1123** [comment]
Attempting to address by #70
