### ISSUE TITLE
Include test name in the test execution and aggregate reports.

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#66]
Determine if it's possible to include the actual test name in the test execution and test execution aggregate reports.

If so (and, it should be):

- [ ] Add to both report objects.
- [ ] Expose in the UI.

**Comment by jiujiu1123** [comment]
Wouldn't the name for the test exeuction and the aggregate report be the same modulo the test exeuction should have the iteration number?

**Comment by cmeiklejohn** [comment]
I'm looking here for the test name as in the 'DisplayName' attribute on the junit test if set, otherwise the test's function name.

**Comment by cmeiklejohn** [comment]
I just want them rendered in both reports, so that's why I said to have the attribute on both.

**Comment by cmeiklejohn** [comment]
This is so someone reading the HTML report knows which code ran

**Comment by jiujiu1123** [comment]
Gotcha! I just want to make sure you don't want "Filibuster Generated Test #1"  for isntance. Rn i am grabbing the parent of the test execution and grabbing their name, which should be the name of the test

**Comment by cmeiklejohn** [comment]
There is probably a way to pull the attribute, if it's defined, and add it to the configuration object in the FilibusterTestExtension.  If the display name attribute isn't set, it might take a bit of reflection or something else to figure out the test name but it should be possible because junit uses this information.

**Comment by cmeiklejohn** [comment]
Eventually, we're gonna do other stuff with this in the analysis to determine redundant tests, but for now, let's just display it in the report.

**Comment by jiujiu1123** [comment]
Gotcha

**Comment by cmeiklejohn** [comment]
This was done, I think.
