### ISSUE TITLE
Update GitHub actions to make the checks required for merge.

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#71]

**Comment by jiujiu1123** [comment]
I am guesssing that does not extend to the sonotype one? That one seems to have a bit more false positives

**Comment by jiujiu1123** [comment]
Never mind, got your comment notification legit the same time as I commented the previous one

**Comment by jiujiu1123** [comment]
I think I might not have enough permission on Github to perform this

**Comment by cmeiklejohn** [comment]
Looks like this has to be done organization wide in a way that's not quite possible at the moment.  Won't fix.
