### ISSUE TITLE
Missing 1.1.15 release.

### ISSUE THREAD

**Issue by cmeiklejohn** [filibuster-testing/filibuster-java-instrumentation#73]
Because of an issue with Maven Central, 1.1.15 was pushed without the release being tagged.  We have a problem here because if we tag the 1.1.15 commit on here, it won't have an associated build.gradle commit updating the version number.  Therefore, we need to retract the release from Maven Central, if possible, for consistency.

**Comment by jiujiu1123** [comment]
I am not sure if it's possible to "retract" an artifact on maven central, as a rule. I can try to contact the sonotype folks to override it. Do you want me to do so?

**Comment by cmeiklejohn** [comment]
No, that's fine.  We'll just ignore this.
